### ISSUE TITLE
The library doesn't seem to be complete

### ISSUE THREAD

**Issue by d2callpod** [canopas/compose-intro-showcase#10]
There are quite a few things that are not in the library,
`fun Modifier.introShowCaseTarget`, `fun rememberIntroShowCaseState`, `fun IntroShowCaseScaffold`, etc. 

I'm trying `com.canopas.intro-showcase-view:introshowcaseview:1.0.5`.

**Comment by Macksly** [comment]
I am experiencing this aswel, did you figure it out?

**Comment by d2callpod** [comment]
I've copied this into my project.

https://github.com/canopas/Intro-showcase-view/blob/4a459a9baeca3480ede3d8b2cfe716ed4317d6ac/showcase/src/main/java/com/canopas/lib/showcase/IntroShowCase.kt

**Comment by cp-radhika-s** [comment]
> There are quite a few things that are not in the library, `fun Modifier.introShowCaseTarget`, `fun rememberIntroShowCaseState`, `fun IntroShowCaseScaffold`, etc.
> 
> I'm trying `com.canopas.intro-showcase-view:introshowcaseview:1.0.5`.

@d2callpod Thanks for reporting the issue.

Can you please try with

`com.canopas.intro-showcase-view:introshowcaseview:1.0.7`

**Comment by d2callpod** [comment]
Looks like there has been some refactoring since the version I copy and pasted as well as the example app and blog post. The constructor takes a state rather than targets, now there is a scaffold... I don't have time to figure this out right now. I've moved onto another project.

**Comment by d2callpod** [comment]
I've tried `1.0.7` and it works well. Thank you for the update.

Maybe this should be a separate issue but the circle is very big on tablets and phones in landscape.


![Screenshot_20220819_190821-smaller](https://user-images.githubusercontent.com/4429507/185725281-460a3ee3-d801-40ef-8aa8-7f48e87d2820.png)

![Screenshot_20220819_191535](https://user-images.githubusercontent.com/4429507/185725389-44e58817-2d37-49cb-886d-06190d6a1a89.png)

Looks good on a phone in portrait. 

![Screenshot_20220819_1913442](https://user-images.githubusercontent.com/4429507/185725344-9e4fee67-8c99-465f-be6b-a7e52218d934.png)

**Comment by cp-radhika-s** [comment]
> I've tried `1.0.7` and it works well. Thank you for the update.
> Maybe this should be a separate issue but the circle is very big on tablets and phones in landscape.



@d2callpod Thank for taking interest 
 can you please create new issue for this?
