### ISSUE TITLE
On a fullscreen app (Edge to edge), showcase Y coords are offset

### ISSUE THREAD

**Issue by jscti** [canopas/compose-intro-showcase#12]
Showcase is offset when using :

```
WindowCompat.setDecorFitsSystemWindows(window, false)

setContent {
    Surface(
                    modifier = Modifier
                        .background(colorResource(id = R.color.colorSurface))
                        .systemBarsPadding()
                ) {
                    // IntroShowCaseScaffold( ....
                }
}
```

using lib with 1.07 version
The target element is the settings icon :

![image](https://user-images.githubusercontent.com/1594035/197361159-04c77732-0e54-4ddc-b734-78da6026be5a.png)

**Comment by cp-radhika-s** [comment]
Closing this issue since this issue has been fixed in version 2.0.0. Thanks for reporting this issue!
