### ISSUE TITLE
Restart intro on demand.

### ISSUE THREAD

**Issue by realstaticvoid** [canopas/compose-intro-showcase#21]
Hello. I can not find a solution to restart the intro on users demand. I tried to reassign the state via 
[rememberIntroShowcaseState](https://github.com/canopas/compose-intro-showcase/blob/master/showcase/src/main/java/com/canopas/lib/showcase/component/ShowCasestate.kt#L23) and implemented some other ideas but it does not work. Any ideas how to achieve that with the latest version?

**Comment by cp-megh-l** [comment]
Hi @aphex- 
You can now restart intro using `state.reset()` available in version `2.0.1`. Checkout `sample-app` for more details.
