### ISSUE TITLE
Is there a way to use this library as FancyShowcaseView ?

### ISSUE THREAD

**Issue by Elaws** [canopas/compose-intro-showcase#26]
In [FancyShowcaseView](https://github.com/faruktoptas/FancyShowCaseView), we could design a "tutorial" mode, where a chosen clicked UI element would show its tutorial.

The process was as follow :

1. Activate showcase mode (e.g. by clicking on a "tutorial" button).
2. Click on UI element you need help for and it will display its help.
3. Click anywhere to dismiss and choose another UI element.
4. Disable showcase mode by clicking again on "tutorial" button.

Is there any way to make compose-intro-showcase fit this workflow ?

Thank you.

**Comment by cp-radhika-s** [comment]
@Elaws Thank you for the suggestion! While we're not planning to add support for this specific workflow, we will keep it in mind for future updates.
